[platformio]
default_envs = t8
src_dir = platforms/pio

[env:t8]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.f_cpu = 240000000L
lib_deps =
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git#3.0.14
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
  adafruit/Adafruit SSD1306
  adafruit/Adafruit NeoPixel
  h2zero/NimBLE-Arduino@1.4.3
extra_scripts = pre:platforms/pio/extra_firmware.py
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -mfix-esp32-psram-cache-strategy=memw
  -DKOTO_BA1P_SYMBOLS
  -DCORE_DEBUG_LEVEL=0
  -I firmware/include
  -I platforms/pio
