// GENERATED by tools/bsod_atlas.py — do not edit.
#include "koto/assets/bsod.hpp"

namespace koto {
namespace assets {
namespace {

const std::uint8_t kBsod_sad[] = {
    0x02, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xE0, 0x03, 0xF8, 0x01, 0x1E, 0x00, 0x80, 0x00,
    0x20, 0x00, 0x08, 0x38, 0x02, 0x0E, 0x00, 0x83, 0x80, 0x20, 0x00, 0x04, 0x40, 0x00, 0xF0, 0x00,
    0x00, 0x00, 0x00
};

const std::uint8_t kBsod_bar[] = {
    0x01, 0x01, 0xFF, 0xFF, 0xFF, 0x80, 0x00
};

}  // namespace

const BsodSprite kBsodSprites[] = {
    {"sad", 18, 12, kBsod_sad, sizeof(kBsod_sad)},
    {"bar", 64, 2, kBsod_bar, sizeof(kBsod_bar)},
};
const int kBsodSpriteCount = static_cast<int>(sizeof(kBsodSprites) / sizeof(kBsodSprites[0]));

const BsodSprite* find_bsod_sprite(std::string_view id) {
  for (int i = 0; i < kBsodSpriteCount; ++i) {
    if (id == kBsodSprites[i].id) {
      return &kBsodSprites[i];
    }
  }
  return nullptr;
}

}  // namespace assets
}  // namespace koto
