// GENERATED by tools/dvd_atlas.py — do not edit.
#include "koto/assets/dvd.hpp"

namespace koto {
namespace assets {
namespace {

const std::uint8_t kDvd_logo[] = {
    0x02, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x01, 0xFF, 0x80, 0x0F, 0xFF, 0xF0, 0x38, 0xA8,
    0xFC, 0x7A, 0xAA, 0xFE, 0xFA, 0xAA, 0xFF, 0xFA, 0xDA, 0xFF, 0xF8, 0xD8, 0xFF, 0x7F, 0xFF, 0xFE,
    0x3C, 0x00, 0x3C, 0x0F, 0xFF, 0xF0, 0x01, 0xFF, 0x80
};

}  // namespace

const DvdSprite kDvdSprites[] = {
    {"logo", 24, 11, kDvd_logo, sizeof(kDvd_logo)},
};
const int kDvdSpriteCount = static_cast<int>(sizeof(kDvdSprites) / sizeof(kDvdSprites[0]));

const DvdSprite* find_dvd_sprite(std::string_view id) {
  for (int i = 0; i < kDvdSpriteCount; ++i) {
    if (id == kDvdSprites[i].id) {
      return &kDvdSprites[i];
    }
  }
  return nullptr;
}

}  // namespace assets
}  // namespace koto
