// GENERATED by tools/spectrum_atlas.py — do not edit.
#include "koto/assets/spectrum.hpp"

namespace koto {
namespace assets {
namespace {

const std::uint8_t kSpectrum_peak[] = {
    0x02, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x54
};

const std::uint8_t kSpectrum_baseline[] = {
    0x02, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};

}  // namespace

const SpectrumSprite kSpectrumSprites[] = {
    {"peak", 3, 2, kSpectrum_peak, sizeof(kSpectrum_peak)},
    {"baseline", 64, 2, kSpectrum_baseline, sizeof(kSpectrum_baseline)},
};
const int kSpectrumSpriteCount = static_cast<int>(sizeof(kSpectrumSprites) / sizeof(kSpectrumSprites[0]));

const SpectrumSprite* find_spectrum_sprite(std::string_view id) {
  for (int i = 0; i < kSpectrumSpriteCount; ++i) {
    if (id == kSpectrumSprites[i].id) {
      return &kSpectrumSprites[i];
    }
  }
  return nullptr;
}

}  // namespace assets
}  // namespace koto
